version: "2"

run:
  relative-path-mode: gomod
  concurrency: 8
  issues-exit-code: 1
  tests: true

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - copyloopvar
    - cyclop
    - decorder
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    #- forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    # - gocognit
    - goconst
    - godot
    - goprintffuncname
    - govet
    - inamedparam
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    # - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    revive:
      confidence: 0.1
      rules:
        - name: exported
          disabled: true
    errcheck:
      check-type-assertions: true
      check-blank: false
    testifylint:
      enable-all: true
    govet:
      enable-all: true
      disable:
        - shadow
    lll:
      line-length: 170
    funlen:
      ignore-comments: true
    nolintlint:
      allow-unused: false
      allow-no-explanation: []
      require-explanation: true
      require-specific: true
    gocognit:
      min-complexity: 15
    cyclop:
      max-complexity: 15
    nakedret:
      max-func-lines: 0
  exclusions:
    #   generated: lax
    #   rules:
    #     - linters:
    #         - gocritic
    #       source: //noinspection
    #     - linters:
    #         - bodyclose
    #         - dupl
    #         - funlen
    #         - gochecknoglobals
    #         - goconst
    #         - gosec
    #         - noctx
    #         - wrapcheck
    #       path: _test\.go
    #     - path: (.+)\.go$
    #       text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
    #     - path: (.+)\.go$
    #       text: should check returned error before deferring
    paths:
      - bin
      - builtin$
      - examples$
      - third_party$
      - tmp
      - var
      - vendor
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - builtin$
      - examples$
      - tmp
      - var
      - vendor
